//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCA_LeahuLorena.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDigitalSignature")]
    public interface IDigitalSignature {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalSignature/Sha256Sign", ReplyAction="http://tempuri.org/IDigitalSignature/Sha256SignResponse")]
        byte[] Sha256Sign(byte[] hash, string certificateSubject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalSignature/Sha256Sign", ReplyAction="http://tempuri.org/IDigitalSignature/Sha256SignResponse")]
        System.Threading.Tasks.Task<byte[]> Sha256SignAsync(byte[] hash, string certificateSubject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDigitalSignatureChannel : WebCA_LeahuLorena.ServiceReference1.IDigitalSignature, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitalSignatureClient : System.ServiceModel.ClientBase<WebCA_LeahuLorena.ServiceReference1.IDigitalSignature>, WebCA_LeahuLorena.ServiceReference1.IDigitalSignature {
        
        public DigitalSignatureClient() {
        }
        
        public DigitalSignatureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitalSignatureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalSignatureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalSignatureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] Sha256Sign(byte[] hash, string certificateSubject) {
            return base.Channel.Sha256Sign(hash, certificateSubject);
        }
        
        public System.Threading.Tasks.Task<byte[]> Sha256SignAsync(byte[] hash, string certificateSubject) {
            return base.Channel.Sha256SignAsync(hash, certificateSubject);
        }
    }
}
